### PR TITLE
user_guide.md: change format of bulleted lists to tables

### PR DESCRIPTION
**Pull request by gx1400**

### CODE REVIEW

**Comment by silseva** [comment]
Can you please also add the documentation for buttons 7 and 8 in the macro menu?
7 decreases brightness and 8 increases it.

Thank you! :)

**Comment by gx1400** [comment]
Absolutely.  

Apologize, I have an RT3S/MD-UV380 and B+/B- do not show on my unit.

I just found the documentation about not supporting the backlight after the discussions on Discord and in https://github.com/OpenRTX/OpenRTX/blob/master/platform/targets/MD-UV3x0/hwconfig.h

Will add and commit

**Comment by silseva** [comment]
No worries! We'll add backlight control also on the UV380, by the way.
Thank you!

**Comment by gx1400** [comment]
Brightness Commited @silseva

**Pull request merged**
