### PR TITLE
md-uv380: add windows drivers and manufacturer flashing firmware inst…

### PR DESCRIPTION
**Pull request by gx1400**
…ructions

### CODE REVIEW

**Comment by silseva** [comment]
Great work, thank you!
Just a couple of notes:
- in the md-uv380 guide there is a "place link to ... here" note. Do you have the actual url, so that we can update the document?
- the procedure works also for the MD-380 series of radios, I'll make the guide generic for all the MDx devices. The only thing to change is the title.

I'll merge it in the next days as now I don't have the computer available.

**Comment by gx1400** [comment]
@silseva  `in the md-uv380 guide there is a "place link to ... here" note. Do you have the actual url, so that we can update the document?`

Could you point me toward that?  I'm struggling to find it

**Comment by gx1400** [comment]
I appear to be missing "../_media/drivers_stm32_dfumodeSuccess.jpg" on line 49 of win-stm32drivers.md

I need to check my laptop to see if I forgot to push that file or if it's in the wrong place

**Comment by silseva** [comment]
> @silseva `in the md-uv380 guide there is a "place link to ... here" note. Do you have the actual url, so that we can update the document?`
> 
> Could you point me toward that? I'm struggling to find it

I was referring to this line https://github.com/OpenRTX/openrtx.github.io/blob/a01a0ccfc28c67286eefaeccd0f27ac4ebaf97f7/flashing/md-win.md?plain=1#L19
But apparently I misread it while looking at the markdown file. If you can add a link, good, otherwise nevermind. :)

Thank you!

**Comment by gx1400** [comment]
I checked my laptop and I do not appear to have the stm32 dfu image that is missing.

I left my USB cable at my parents over the holidays, so I don't currently have a cable available to take a new screenshot

**Comment by silseva** [comment]
I'll download the exe file and host it somewhere, is always a good idea to provide our own mirror as things on internet tend to magically disappear from time to time

**Comment by gx1400** [comment]
http://47.253.5.16/soft/FirmwareDownloadV3.04_EN.exe

**Comment by silseva** [comment]
Also this: https://www.hamdigitaal.nl/download/firmware/tyt_firmware/FirmwareDownloadV3.04_EN.exe

**Comment by gx1400** [comment]
> Also this: https://www.hamdigitaal.nl/download/firmware/tyt_firmware/FirmwareDownloadV3.04_EN.exe

Yes, as you said, I'm generally hesitant to link files to others websites in case the file is moved or link goes dead.

I have been unsure about hosting third party software files, if there are any licensing or other concerns. 

Links provided and do with it what you think is best!

**Comment by gx1400** [comment]
@silseva fixed the dead image link, I think it was a renamed image.  I think ultimately it may have been a replicated image, so told it to link to a section of the same page above.  

I think this may be ready for merge with your approval

**Comment by silseva** [comment]
Thank you! I'll merge it in the next days.

**Comment by silseva** [comment]
Thank you!

**Pull request merged**
